version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels"
    columns:
      - name: channel_key
        description: "Primary key (hash of channel name)"
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Date dimension for time-based analysis"
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: "Fact table containing all telegram messages"
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "Foreign key to dim_dates"
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
